import { useEffect, useState } from 'react'
import { api } from '../api'
import type { EditStyleProfile, GenerationConfig } from '../types'
import { CAPTION_PRESETS, LAYOUT_PRESETS, captionPresetForConfig } from '../creativePresets'

interface Props { source?: string; file?: File | null; onBack: () => void; onProcess: (config: GenerationConfig) => void | Promise<void> }
const initialConfig: GenerationConfig = { config_version: 1, style_profile_id: 'publikclip-default', layout: { preset_id: 'vertical_9_16', target_aspect_ratio: '9:16' }, captions: { preset_id: 'hormozi', enabled: true, fill: 'white' }, broll: { mode: 'off', presentation: 'mixed' }, sfx: { mode: 'off' }, music: { mode: 'off' }, title_hook: { mode: 'profile_default', enabled: true }, camera: { speaker_change: 'cut', pan_duration_s: .6, deadzone_frac: .05, punch: { enabled: true, intensity: 1 }, zoom_lock_per_scene: true }, transitions: { mode: 'none' }, user_overrides: {} }
type Tab = 'featured' | 'mine' | 'brand'
type LengthChoice = 'any' | 'under30' | '30to60' | '60to90' | '90to180' | 'over180'
const lengths: Array<[LengthChoice, string]> = [['any', 'Any length'], ['under30', '<30s'], ['30to60', '30–60s'], ['60to90', '60–90s'], ['90to180', '90s–3min'], ['over180', '>3min']]
const lengthRanges: Record<LengthChoice, GenerationConfig['clip_length']> = { any: { min_seconds: null, max_seconds: null }, under30: { min_seconds: null, max_seconds: 30 }, '30to60': { min_seconds: 30, max_seconds: 60 }, '60to90': { min_seconds: 60, max_seconds: 90 }, '90to180': { min_seconds: 90, max_seconds: 180 }, over180: { min_seconds: 180, max_seconds: null } }
const choiceLabel = (value: string | undefined, labels: Record<string, string>) => labels[value || ''] || value || 'Default'

function Badge({ children, tone = 'muted' }: { children: React.ReactNode; tone?: 'muted' | 'active' | 'prep' }) { return <span className={`setup-badge ${tone}`}>{children}</span> }
function Preview({ id, title }: { id: string; title?: boolean }) { const preset = CAPTION_PRESETS.find((item) => item.id === id) || CAPTION_PRESETS[0]; const fill = String(preset.preview.fill); const color = fill === 'yellow' ? '#ffe26f' : fill === 'cyan' ? '#8ae9ef' : '#fff'; return <div className={`setup-template-preview preview-${id}`}><div className="setup-preview-video"><span /><span /><span /></div>{title && <div className="setup-preview-title">YOUR<br />MOMENT</div>}<div className="setup-preview-caption" style={{ color }}><b>{preset.preview.highlight || 'MAKE IT'}</b><span>{preset.name === 'Minimal' ? 'simple.' : 'UNMISSABLE'}</span></div><div className="setup-preview-progress" /></div> }

export default function CreativeSetupV2({ source, file, onBack, onProcess }: Props) {
  const [profiles, setProfiles] = useState<EditStyleProfile[]>([]); const [config, setConfig] = useState<GenerationConfig>(initialConfig); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [tab, setTab] = useState<Tab>('featured'); const [lengthChoice, setLengthChoice] = useState<LengthChoice>('any'); const [findMoment, setFindMoment] = useState(''); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [overridden, setOverridden] = useState<Set<string>>(new Set())
  useEffect(() => { let active = true; api.listStyleProfiles().then(({ profiles: loaded }) => { if (!active) return; setProfiles(loaded); const profile = loaded.find((item) => item.is_default) || loaded[0]; if (profile) setConfig((current) => ({ ...current, style_profile_id: current.style_profile_id || profile.id, layout: { ...profile.config.layout, ...current.layout }, captions: { ...profile.config.captions, ...current.captions } })) }).catch((err) => active && setError(err instanceof Error ? err.message : 'Could not load style profiles.')).finally(() => active && setLoading(false)); return () => { active = false } }, [])
  useEffect(() => { if (!file) { setPreviewUrl(null); return }; const url = URL.createObjectURL(file); setPreviewUrl(url); return () => URL.revokeObjectURL(url) }, [file])
  const selectedCaption = captionPresetForConfig(config.captions?.preset_id)
  const setSection = <K extends keyof GenerationConfig>(section: K, value: GenerationConfig[K]) => { setConfig((current) => ({ ...current, [section]: value })); if (section !== 'style_profile_id') setOverridden((current) => new Set(current).add(String(section))) }
  const selectProfile = (profile: EditStyleProfile) => setConfig((current) => ({ ...current, style_profile_id: profile.id, layout: overridden.has('layout') ? current.layout : { ...current.layout, ...profile.config.layout }, captions: overridden.has('captions') ? current.captions : { ...current.captions, ...profile.config.captions } }))
  const selectCaption = (id: string) => { const preset = CAPTION_PRESETS.find((item) => item.id === id); if (preset) setSection('captions', { ...config.captions, ...preset.config }) }
  const process = async () => { setSaving(true); setError(null); try { await onProcess(config) } catch (err) { setSaving(false); setError(err instanceof Error ? err.message : 'Could not save creative setup.') } }
  const title = file?.name || source || 'Untitled source'; const meta = file ? `${(file.size / 1024 / 1024).toFixed(1)} MB · Upload ready` : 'Source link ready'
  return <div className="creative-setup-page setup-v2">
    <header className="setup-v2-header"><button className="creative-back" onClick={onBack}>← Back</button><div className="setup-brand-lockup"><span className="setup-brand-dot">✦</span><span>Creative setup</span></div><span className="setup-step">STEP 2 OF 3</span></header>
    <main className="setup-v2-main"><div className="setup-v2-heading"><div><span className="setup-eyebrow">MAKE IT YOURS</span><h1>Set the creative direction.</h1><p>Start with a template. Everything else can stay simple.</p></div><Badge tone="active">AI-assisted</Badge></div>{error && <div className="creative-error" role="alert">{error}</div>}
      <section className="setup-source-card"><div className="setup-source-thumb">{previewUrl ? <video src={previewUrl} muted /> : <div className="setup-source-placeholder"><span>▶</span></div>}</div><div className="setup-source-copy"><span className="setup-eyebrow">SOURCE VIDEO</span><strong title={title}>{title}</strong><span>{meta}</span></div><Badge tone={loading ? 'muted' : 'active'}>{loading ? 'Loading profile' : 'Ready to create'}</Badge></section>
      <section className="setup-choice-row"><div className="setup-choice-card"><div className="setup-card-label"><span>Canvas ratio</span><Badge tone="active">Active</Badge></div><div className="setup-segmented setup-ratio-options">{(['9:16', '1:1', '16:9'] as const).map((ratio) => <button key={ratio} className={`${config.layout?.target_aspect_ratio === ratio ? 'selected' : ''} ${ratio !== '9:16' ? 'prep' : ''}`} disabled={ratio !== '9:16'} onClick={() => ratio === '9:16' && setSection('layout', { ...config.layout, preset_id: 'vertical_9_16', target_aspect_ratio: ratio })}>{ratio}{ratio !== '9:16' && <small>Soon</small>}</button>)}</div><p className="setup-help">Vertical is the currently supported output.</p></div><div className="setup-choice-card"><div className="setup-card-label"><span>Clip length</span><Badge>Selection range</Badge></div><div className="setup-segmented setup-length-options">{lengths.map(([id, text]) => <button key={id} className={lengthChoice === id ? 'selected' : ''} onClick={() => { setLengthChoice(id); setSection('clip_length', lengthRanges[id]) }}>{text}</button>)}</div><p className="setup-help">Selected bounds are applied to candidate selection.</p></div></section>
      <section className="setup-panel setup-templates"><div className="setup-panel-heading"><div><span className="setup-eyebrow">STYLE LIBRARY</span><h2>Choose a template</h2></div><span className="setup-panel-note">Existing presets · no media rendering</span></div><div className="setup-tabs" role="tablist">{([['featured', 'Featured'], ['mine', 'My templates'], ['brand', 'Brand templates']] as const).map(([id, text]) => <button key={id} role="tab" aria-selected={tab === id} className={tab === id ? 'selected' : ''} onClick={() => setTab(id)}>{text}{id !== 'featured' && <span className="setup-tab-count">{id === 'mine' ? profiles.length : 0}</span>}</button>)}</div>
        {tab === 'featured' && <div className="setup-template-grid">{CAPTION_PRESETS.map((preset, index) => <button key={preset.id} className={`setup-template-card ${config.captions?.preset_id === preset.config.preset_id ? 'selected' : ''}`} onClick={() => selectCaption(preset.id)}><Preview id={preset.id} title={index === 1 || index === 2} /><span className="setup-template-meta"><strong>{preset.name}</strong><small>{preset.description}</small></span>{config.captions?.preset_id === preset.config.preset_id && <span className="setup-selected-mark">✓</span>}</button>)}</div>}
        {tab === 'mine' && <div className="setup-profile-grid">{profiles.map((profile) => <button key={profile.id} className={`setup-profile-card ${config.style_profile_id === profile.id ? 'selected' : ''}`} onClick={() => selectProfile(profile)}><span className="setup-profile-avatar">✦</span><span><strong>{profile.name}</strong><small>{profile.description || 'Saved style profile'}</small></span>{config.style_profile_id === profile.id && <span className="setup-selected-mark">✓</span>}</button>)}{!loading && !profiles.length && <div className="setup-empty">No saved templates yet.</div>}</div>}
        {tab === 'brand' && <div className="setup-empty setup-brand-empty"><span>✦</span><strong>Brand templates are coming soon.</strong><small>Saved style profiles remain available in My templates.</small></div>}
      </section>
      <section className="setup-panel setup-quick"><div className="setup-panel-heading"><div><span className="setup-eyebrow">QUICK OPTIONS</span><h2>Keep it focused</h2></div><span className="setup-panel-note">Your defaults stay intact</span></div><div className="setup-option-grid">
        <label className="setup-option-row"><span className="setup-option-icon">Aa</span><span><strong>Captions</strong><small>{selectedCaption?.name || 'Custom'} · active output</small></span><input type="checkbox" checked={config.captions?.enabled !== false} onChange={(event) => setSection('captions', { ...config.captions, enabled: event.target.checked })} /><i /></label>
        <div className="setup-option-row"><span className="setup-option-icon">✦</span><span><strong>Keyword emphasis</strong><small>Uses the selected caption preset</small></span><Badge tone={selectedCaption?.id === 'highlight' ? 'active' : 'muted'}>{selectedCaption?.id === 'highlight' ? 'On' : 'Preset'}</Badge></div>
        <label className="setup-option-row"><span className="setup-option-icon">◐</span><span><strong>Caption fill</strong><small>Active renderer color</small></span><select value={config.captions?.fill || 'white'} onChange={(event) => setSection('captions', { ...config.captions, fill: event.target.value as 'white' | 'yellow' | 'cyan' })}><option value="white">White</option><option value="yellow">Yellow</option><option value="cyan">Cyan</option></select></label>
        <label className="setup-option-row"><span className="setup-option-icon">▧</span><span><strong>B-roll policy</strong><small>Choose mode and presentation</small></span><span className="setup-double-select"><select value={config.broll?.mode || 'off'} onChange={(event) => setSection('broll', { ...config.broll, mode: event.target.value as NonNullable<GenerationConfig['broll']>['mode'] })}><option value="off">Off</option><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select><select value={config.broll?.presentation || 'mixed'} onChange={(event) => setSection('broll', { ...config.broll, presentation: event.target.value as NonNullable<GenerationConfig['broll']>['presentation'] })}><option value="mixed">Mixed</option><option value="replace">Replace</option><option value="overlay">Overlay</option></select></span></label>
        <div className="setup-option-row setup-option-disabled"><span className="setup-option-icon">◌</span><span><strong>Remove silences</strong><small>Semantic compression preparation</small></span><Badge tone="prep">Preparation</Badge></div>
        <div className="setup-option-row setup-option-disabled"><span className="setup-option-icon">⌕</span><span><strong>Find clip moment</strong><small>Search is not connected to this setup yet</small></span><Badge tone="prep">Preparation</Badge></div>
        <label className="setup-option-row"><span className="setup-option-icon">T</span><span><strong>Title hook</strong><small>{choiceLabel(config.title_hook?.mode, { profile_default: 'Profile default', none: 'Off', generated: 'Generated', manual: 'Manual' })}</small></span><select value={config.title_hook?.mode || 'profile_default'} onChange={(event) => setSection('title_hook', { ...config.title_hook, mode: event.target.value as NonNullable<GenerationConfig['title_hook']>['mode'], enabled: event.target.value !== 'none' })}><option value="profile_default">Profile default</option><option value="none">Off</option><option value="generated">Generated</option><option value="manual">Manual</option></select></label>
      </div><div className="setup-find-moment"><label htmlFor="find-moment">Find clip moment <span>Optional</span></label><input id="find-moment" value={findMoment} onChange={(event) => setFindMoment(event.target.value)} disabled placeholder="When they talk about..." /><Badge tone="prep">Preparation only</Badge></div></section>
      <details className="setup-panel setup-advanced"><summary><span><span className="setup-eyebrow">MORE CONTROL</span><h2>Advanced settings</h2></span><span className="setup-advanced-summary">SFX · music · framing · camera <b>⌄</b></span></summary><div className="setup-advanced-body"><label><span>Layout preset</span><select value={config.layout?.preset_id || 'vertical_9_16'} onChange={(event) => { const preset = LAYOUT_PRESETS[event.target.value]; if (preset) setSection('layout', { ...config.layout, ...preset.config }) }}>{Object.values(LAYOUT_PRESETS).map((preset) => <option key={preset.id} value={preset.id}>{preset.name}{preset.renderer_support === 'preparation_only' ? ' · soon' : ''}</option>)}</select></label><label><span>SFX policy</span><select value={config.sfx?.mode || 'off'} onChange={(event) => setSection('sfx', { ...config.sfx, mode: event.target.value as NonNullable<GenerationConfig['sfx']>['mode'] })}><option value="off">Off</option><option value="minimal">Minimal</option><option value="balanced">Balanced</option><option value="punchy">Punchy</option></select></label><label><span>Music policy</span><select value={config.music?.mode || 'off'} onChange={(event) => setSection('music', { ...config.music, mode: event.target.value as NonNullable<GenerationConfig['music']>['mode'] })}><option value="off">Off</option><option value="low">Low</option><option value="medium">Medium</option></select></label><label><span>Speaker change</span><select value={config.camera?.speaker_change || 'cut'} onChange={(event) => setSection('camera', { ...config.camera, speaker_change: event.target.value as 'cut' | 'pan' | 'locked' })}><option value="cut">Cut</option><option value="pan">Pan</option><option value="locked">Locked</option></select></label><label><span>Pan duration</span><input type="number" min="0" max="3" step="0.1" value={config.camera?.pan_duration_s ?? .6} onChange={(event) => setSection('camera', { ...config.camera, pan_duration_s: Number(event.target.value) })} /></label><label className="setup-check"><input type="checkbox" checked={config.camera?.punch?.enabled !== false} onChange={(event) => setSection('camera', { ...config.camera, punch: { ...config.camera?.punch, enabled: event.target.checked } })} /><span>Punch in</span></label><label className="setup-check"><input type="checkbox" checked={config.camera?.zoom_lock_per_scene !== false} onChange={(event) => setSection('camera', { ...config.camera, zoom_lock_per_scene: event.target.checked })} /><span>Lock zoom per scene</span></label>{config.title_hook?.mode === 'manual' && <label className="setup-manual-hook"><span>Manual title hook</span><input value={config.title_hook.manual_text || ''} onChange={(event) => setSection('title_hook', { ...config.title_hook, manual_text: event.target.value })} placeholder="Write the opening title hook…" /></label>}</div></details>
      <div className="setup-final"><div><span className="setup-eyebrow">READY WHEN YOU ARE</span><h2>Create your first cut.</h2><p>{selectedCaption?.name || 'Selected'} template · {config.layout?.target_aspect_ratio || '9:16'} · {lengths.find(([id]) => id === lengthChoice)?.[1]}</p></div><button className="setup-primary-cta" onClick={process} disabled={saving || loading}>{saving ? 'Saving setup…' : 'Create AI clips'}<span>→</span></button></div><button className="setup-bottom-back" onClick={onBack}>← Back to source</button>
    </main></div>
}
