import type { JobResults } from '../types'
import { api } from '../api'

function fmt(t: number) { const m = Math.floor(t / 60); return `${m}:${String(Math.floor(t % 60)).padStart(2, '0')}` }

interface Props { results: JobResults; onBack: () => void; onOpenClip: (index: number) => void; onOpenAnalytics: () => void; onOpenLoop: () => void; onOpenQueue: () => void; onOpenTranscribeQueue: () => void }
export default function ProjectClips({ results, onBack, onOpenClip, onOpenAnalytics, onOpenLoop, onOpenQueue, onOpenTranscribeQueue }: Props) {
  const outputs = results.render?.outputs ?? []
  const clips = results.score?.clips ?? []
  const title = results.ingest?.title || 'Untitled project'
  return <div className="project-view"><aside className="project-view-side"><button className="project-back" onClick={onBack}>← Back to workspace</button><div className="project-view-brand">✦ clipizator</div><div className="project-view-nav"><button onClick={onOpenAnalytics}>◔ Analytics</button><button className="selected">▶ Clips</button><button onClick={onOpenAnalytics}>▤ Campaigns</button></div><div className="project-side-bottom"><button onClick={onOpenLoop}>◌ Instagram loop</button><button onClick={onOpenQueue}>↓ Download queue</button><button onClick={onOpenTranscribeQueue}>◉ Transcribe queue</button></div></aside><main className="project-view-main"><header className="project-view-head"><div><p className="new-eyebrow">PROJECT / GENERATED CLIPS</p><h1>{title}</h1><p>{outputs.length} clips · {results.ingest?.probe ? fmt(results.ingest.probe.duration_sec) : '—'} source video</p></div><button className="new-primary">＋ Add to campaign</button></header><div className="project-clip-toolbar"><b>All clips</b><span>{outputs.length} generated from this video</span><button>Sort by score ↓</button></div><div className="project-clips-grid">{outputs.map((out, i) => { const clip = clips[out.clip]; return <button className="project-clip-card" key={out.clip} onClick={() => onOpenClip(i)}><div className="project-clip-media"><video src={api.previewUrl(results.job_id, out.clip)} muted preload="metadata" /><span className="project-clip-play">▶</span><label>{fmt(out.duration)}</label></div><div className="project-clip-info"><div><b>Clip {String(i + 1).padStart(2, '0')}</b><span className="clip-score">{Math.round(clip?.score ?? out.score)} score</span></div><p>{clip?.headline || clip?.summary || 'Generated highlight from your video'}</p><small>{clip ? `${fmt(clip.start)} – ${fmt(clip.end)} in source` : 'Ready to edit'}</small></div></button> })}</div></main></div>
}
